### ISSUE TITLE
Build actions permissions support

### ISSUE THREAD

**Issue by Constantin07** [atlassian/terraform-provider-artifactory#21]
### Description

Looks like JFrog has now supports both the _Repository Actions permissions_ and _Build Action Permissions_.

### New or Affected Resource(s)

* artifactory_v1.4.3 (artifactory_permission_targets)

### Potential Terraform Configuration

Does the current version support the Build Action permissions too ?
I couldn't find anything in source code/docs about this.

### References

https://www.jfrog.com/confluence/display/RTF/Managing+Permissions

**Comment by dillon-giacoppo** [comment]
The update to the permissions API is relatively new as they slowly build out V2 of their API. I will look at adding support for https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API+V2. It will need to be baked in at the client-library level however so it's non-trivial

**Comment by Constantin07** [comment]
@dillon-giacoppo Thanks for looking into this and getting back so quick. Much appreciated!

Do you think that to support REST API V2 it would be a new resource type, aka _artifactory_permission_targets_v2_ or just an additional attribute to the existing resource ?

**Comment by dillon-giacoppo** [comment]
They are for the most part substitutable. You can check out the refactor on the v2 branch on github.com/atlassian/go-artifactory. The only issue is that the permissions use the full name I.e “read” instead of a letter “r”. There is not a nice way to add this without cutting a new major version or creating a separate resource type. I will look into how existing providers deal with it and get back to you.
