### ISSUE TITLE
remote repository - keeps triggering password change

### ISSUE THREAD

**Issue by Constantin07** [atlassian/terraform-provider-artifactory#24]
### Terraform Version

Terraform v0.11.10
terraform-provider-artifactory 1.4.3

### Affected Resource(s)

* artifactory_remote_repository

### Terraform Configuration Files

```hcl
resource "artifactory_remote_repository" "this" {
  key          = "test-repo"
  package_type = "test-repo"
  url          = "some-url"
  username     = "service_user"
  password     = "<some_password_here>"
}
```

### Expected Behavior

Upon successful run of plan, the next re-run should not trigger password update.

### Actual Behavior

It triggers password update on every re-run.

### Steps to Reproduce

Run terraform plan against above resource.

1. `terraform apply`

### Important Factoids

```
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ artifactory_remote_repository.this
      password: <sensitive> => <sensitive> (attribute changed)


Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------
```

**Comment by dillon-giacoppo** [comment]
Do you have Key Encryption turned on? https://www.jfrog.com/confluence/display/RTF/Artifactory+Key+Encryption. Passwords started to get returned in their encrypted form, since only the artifactory server can decrypt them, there is not currently a good way to diff the passwords. At the moment the only solution is to turn it off. It is not ideal, but I do not believe there is a way to fix it unless JFrog allow these passwords to be decrypted locally. I will update the docs to reflect this

**Comment by Constantin07** [comment]
Thanks @dillon-giacoppo. Yes, by default - which is our case it's enabled encryption.

For the moment the workaround in terraform is to add a lifecycle in remote repository resource:
```hcl
  lifecycle {
    ignore_changes = ["password"]
  }
```
