### ISSUE TITLE
Assign users to group within `artifactory_group` resource

### ISSUE THREAD

**Issue by BattleBrisket** [atlassian/terraform-provider-artifactory#40]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When defining a group, it'd be super helpful to identify users belonging to said group. 

Current use case: my users come in via SAML, and are granted permissions according to team membership.

### New or Affected Resource(s)

`artifactory_group`

### Potential Terraform Configuration

```
# Example block, won't actually work.

resource "artifactory_group" "test-group" {
  name             = "terraform"
  description      = "test group"
  admin_privileges = false

  users = ["user1", "user2"]
}
```

**Comment by dillon-giacoppo** [comment]
While that would be really useful its not really achievable with Artifactory's current API. The group resource does not take members https://www.jfrog.com/confluence/display/RTF/Security+Configuration+JSON. Since terraform is a thin wrapper around the REST API there is nothing we can really do (especially since this would conflict with the users API).

I'd recommend this being raised with JFrog to get incorporated into their V2 API.
