### ISSUE TITLE
Impossible to get user password for newly created user

### ISSUE THREAD

**Issue by bsemperlotti** [atlassian/terraform-provider-artifactory#5]
When creating a new user, a password cannot be specified in terraform but it is automatically generated in the code:
```go
user.Password = artifactory.String(generatePassword())
```
However, the returned User object does not contains any password field and therefore it is impossible to connect to the newly created user.

**Comment by dillon-giacoppo** [comment]
This is expected behaviour, the password can be reset via the forgot password mechanism.

**Comment by mbraku** [comment]
I guess this make sense from a security standpoint.

But consider our following use case:
We have a bot account in Artifactory created with this provider. 
Now we want to run an automated script that resets the bot account's credentials in a fixed interval (let's say once a week or so).
The script should do the following:
1. Generate new random password
2. Provide it to terraform in order to update the user
3. Save it in a secure store from where our CI pipeline can pick it up

Without the means to specify a user's password in this provider we cannot use it. Automating the forgot password mechanism seems a lot more complicated.

Do you know an alternative to our approach that would work with this provider? Thank you

**Comment by dillon-giacoppo** [comment]
@mbraku I agree that the user password not being settable is frustrating but it is not an easy change. 

For context on why the current behaviour is the forgot password mechanism- firstly, terraform has no good way of storing passwords securely in the state file. Our current approach to passwords, as used by the remote repository, is the field is firstly optional and as a small layer of security stored as a md5 hash in the state file. When terraform checks the field it fetches the password from the remote repo config and checks its hash against the hash in the state file.

However, the user endpoint does not return the plaintext password. It is therefore impossible for terraform to verify whether the password has been modified remotely, therefore the user resource would require updating on every run or never be updated.

There is another option. It would be possible to have the password set optionally by an environment variable like TF_USER_my-user_PASSWORD. This will allow passwords to be set on user creation but they will not be managed by terraform. You can secure this password and use the regenerate API key endpoints to get a refreshable "password" for your bot account. Does this solve your use case?

**Comment by rodcloutier** [comment]
@dillon-giacoppo This would probably solve our issue. 

So the provider would pick up the environment variable based on the `artifactory_user` resource name? 

If so, how would you propose to accomodate for users inside modules? 

Could we have a heuristic to detect the name based on the module as well?

**Comment by mbraku** [comment]
@dillon-giacoppo Yes, it would be perfect for us to have the ability to supply passwords via environment variables

**Comment by dillon-giacoppo** [comment]
Fixed in release 1.4.0. You can use the format TF_USER_${username}_PASSWORD where username is the **artifactory** username. This should allow uniqueness and access within modules

**Comment by dillon-giacoppo** [comment]
Closing as fixed in latest release
